Afterpay countries
emspay/ems-online-opencart-3 pull request #7
Opened 2020-06-24 10:42 UTC by LeasoftKonstantinShapoval

2020-08-06 07:54 UTC, tiutiunnykleasoft requested changes

2020-08-06 07:54 UTC, tiutiunnykleasoft commented on upload/admin/language/de-de/extension/payment/emspay_ideal.php
> +$_['info_help_klarna_test_api_key'] = 'Wenn eingegeben, wird dieser API-Schlüssel nur zu Testzwecken verwendet werden.';
Remove empty string, that file isn't changed

2020-08-06 07:54 UTC, tiutiunnykleasoft commented on upload/admin/language/fr-fr/extension/payment/emspay_ideal.php
> +$_['info_help_klarna_test_api_key'] = 'Si entré, cette clé API sera utilisée uniquement à des test.';
Remove empty string

2020-08-06 07:54 UTC, tiutiunnykleasoft commented on upload/admin/language/nl-nl/extension/payment/emspay_ideal.php
> +$_['info_help_klarna_test_api_key'] = 'Vul hier de API Key in van uw test webshop.';
remove empty string

2020-08-06 07:54 UTC, tiutiunnykleasoft commented on upload/catalog/model/extension/payment/emspay_afterpay.php
>              OR zone_id = '0');"
Do these changes actually change something?
If not, remove them

2020-08-06 07:54 UTC, tiutiunnykleasoft commented on upload/system/library/emshelper.php
> +        if ($countryList !== '' ) {
https://github.com/emspay/ems-online-opencart-2/pull/7#discussion_r465632188

2020-08-06 07:54 UTC, tiutiunnykleasoft commented on upload/system/library/emshelper.php
> +    public static function CountryValidator($countryList, $billingAddress)
https://github.com/emspay/ems-online-opencart-2/pull/7#discussion_r465632814

2020-08-06 07:54 UTC, tiutiunnykleasoft commented on upload/admin/view/template/extension/payment/emspay.twig
> +
https://github.com/emspay/ems-online-opencart-2/pull/7#discussion_r465779885

2020-08-11 12:49 UTC, LeasoftKonstantinShapoval commented on upload/catalog/model/extension/payment/emspay_afterpay.php
>              OR zone_id = '0');"
Roll backed.

2020-08-20 15:16 UTC, tiutiunnykleasoft approved these changes

2020-09-07 11:15 UTC, merged